import pandas as pd
from make_soup import File_Soup
from file_soup_methods import Division_Soup
from file_soup_methods import Pool_Soup
from event_info_methods import Teams_Seeds_Teams_Unique_Ordered

class Teams_Division_Dict:
    def __init__(self, teams_list, division):
        self.teams_list = teams_list
        self.division = division
    
    def teams(self):
        return self.teams_list

    def divisions(self):
        event_division = [str(self.division)] * len(self.teams_list)
        return event_division

class Teams_Divisions:
        club_2010_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2010_mixed_nationals_teams_unique_ordered, Division_Soup.club_2010_mixed_nationals_event_division)
        club_2010_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2010_open_nationals_teams_unique_ordered, Division_Soup.club_2010_open_nationals_event_division)
        club_2010_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2010_womxns_nationals_teams_unique_ordered, Division_Soup.club_2010_womxns_nationals_event_division)
        club_2011_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2011_mixed_nationals_teams_unique_ordered, Division_Soup.club_2011_mixed_nationals_event_division)
        club_2011_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2011_open_nationals_teams_unique_ordered, Division_Soup.club_2011_open_nationals_event_division)
        club_2011_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2011_womxns_nationals_teams_unique_ordered, Division_Soup.club_2011_womxns_nationals_event_division)
        club_2012_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2012_mixed_us_open_teams_unique_ordered, Division_Soup.club_2012_mixed_us_open_event_division)
        club_2012_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2012_open_us_open_teams_unique_ordered, Division_Soup.club_2012_open_us_open_event_division)
        club_2012_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2012_womxns_us_open_teams_unique_ordered, Division_Soup.club_2012_womxns_us_open_event_division)
        club_2012_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2012_mixed_nationals_teams_unique_ordered, Division_Soup.club_2012_mixed_nationals_event_division)
        club_2012_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2012_open_nationals_teams_unique_ordered, Division_Soup.club_2012_open_nationals_event_division)
        club_2012_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2012_womxns_nationals_teams_unique_ordered, Division_Soup.club_2012_womxns_nationals_event_division)
        club_2013_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_mixed_us_open_teams_unique_ordered, Division_Soup.club_2013_mixed_us_open_event_division)
        club_2013_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_open_us_open_teams_unique_ordered, Division_Soup.club_2013_open_us_open_event_division)
        club_2013_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_womxns_us_open_teams_unique_ordered, Division_Soup.club_2013_womxns_us_open_event_division)
        club_2013_open_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_open_pe_challenge_teams_unique_ordered, Division_Soup.club_2013_open_pe_challenge_event_division)
        club_2013_womxns_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_womxns_pe_challenge_teams_unique_ordered, Division_Soup.club_2013_womxns_pe_challenge_event_division)
        club_2013_mixed_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_mixed_pe_challenge_teams_unique_ordered, Division_Soup.club_2013_mixed_pe_challenge_event_division)
        club_2013_open_es_challenge_co_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_open_es_challenge_co_teams_unique_ordered, Division_Soup.club_2013_open_es_challenge_co_event_division)
        club_2013_womxns_es_challenge_co_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_womxns_es_challenge_co_teams_unique_ordered, Division_Soup.club_2013_womxns_es_challenge_co_event_division)
        club_2013_mixed_es_challenge_wa_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_mixed_es_challenge_wa_teams_unique_ordered, Division_Soup.club_2013_mixed_es_challenge_wa_event_division)
        club_2013_womxns_esf_challenge_wa_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_womxns_esf_challenge_wa_teams_unique_ordered, Division_Soup.club_2013_womxns_esf_challenge_wa_event_division)
        club_2013_mixed_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_mixed_pf_finale_teams_unique_ordered, Division_Soup.club_2013_mixed_pf_finale_event_division)
        club_2013_open_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_open_pf_finale_teams_unique_ordered, Division_Soup.club_2013_open_pf_finale_event_division)
        club_2013_womxns_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_womxns_pf_finale_teams_unique_ordered, Division_Soup.club_2013_womxns_pf_finale_event_division)
        club_2013_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_mixed_nationals_teams_unique_ordered, Division_Soup.club_2013_mixed_nationals_event_division)
        club_2013_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_open_nationals_teams_unique_ordered, Division_Soup.club_2013_open_nationals_event_division)
        club_2013_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2013_womxns_nationals_teams_unique_ordered, Division_Soup.club_2013_womxns_nationals_event_division)
        club_2014_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_mixed_us_open_teams_unique_ordered, Division_Soup.club_2014_mixed_us_open_event_division)
        club_2014_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_open_us_open_teams_unique_ordered, Division_Soup.club_2014_open_us_open_event_division)
        club_2014_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_womxns_us_open_teams_unique_ordered, Division_Soup.club_2014_womxns_us_open_event_division)
        club_2014_open_pe_challenge_va_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_open_pe_challenge_va_teams_unique_ordered, Division_Soup.club_2014_open_pe_challenge_va_event_division)
        club_2014_womxns_pe_challenge_va_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_womxns_pe_challenge_va_teams_unique_ordered, Division_Soup.club_2014_womxns_pe_challenge_va_event_division)
        club_2014_mixed_pe_challenge_ny_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_mixed_pe_challenge_ny_teams_unique_ordered, Division_Soup.club_2014_mixed_pe_challenge_ny_event_division)
        club_2014_mixed_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_mixed_es_challenge_teams_unique_ordered, Division_Soup.club_2014_mixed_es_challenge_event_division)
        club_2014_open_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_open_es_challenge_teams_unique_ordered, Division_Soup.club_2014_open_es_challenge_event_division)
        club_2014_womxns_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_womxns_es_challenge_teams_unique_ordered, Division_Soup.club_2014_womxns_es_challenge_event_division)
        club_2014_mixed_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_mixed_pf_finale_teams_unique_ordered, Division_Soup.club_2014_mixed_pf_finale_event_division)
        club_2014_open_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_open_pf_finale_teams_unique_ordered, Division_Soup.club_2014_open_pf_finale_event_division)
        club_2014_womxns_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_womxns_pf_finale_teams_unique_ordered, Division_Soup.club_2014_womxns_pf_finale_event_division)
        club_2014_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_mixed_nationals_teams_unique_ordered, Division_Soup.club_2014_mixed_nationals_event_division)
        club_2014_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_open_nationals_teams_unique_ordered, Division_Soup.club_2014_open_nationals_event_division)
        club_2014_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2014_womxns_nationals_teams_unique_ordered, Division_Soup.club_2014_womxns_nationals_event_division)
        club_2015_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_mixed_us_open_teams_unique_ordered, Division_Soup.club_2015_mixed_us_open_event_division)
        club_2015_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_open_us_open_teams_unique_ordered, Division_Soup.club_2015_open_us_open_event_division)
        club_2015_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_womxns_us_open_teams_unique_ordered, Division_Soup.club_2015_womxns_us_open_event_division)
        club_2015_mixed_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_mixed_es_challenge_teams_unique_ordered, Division_Soup.club_2015_mixed_es_challenge_event_division)
        club_2015_open_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_open_es_challenge_teams_unique_ordered, Division_Soup.club_2015_open_es_challenge_event_division)
        club_2015_womxns_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_womxns_es_challenge_teams_unique_ordered, Division_Soup.club_2015_womxns_es_challenge_event_division)
        club_2015_mixed_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_mixed_pe_challenge_teams_unique_ordered, Division_Soup.club_2015_mixed_pe_challenge_event_division)
        club_2015_open_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_open_pe_challenge_teams_unique_ordered, Division_Soup.club_2015_open_pe_challenge_event_division)
        club_2015_womxns_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_womxns_pe_challenge_teams_unique_ordered, Division_Soup.club_2015_womxns_pe_challenge_event_division)
        club_2015_mixed_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_mixed_sf_invite_teams_unique_ordered, Division_Soup.club_2015_mixed_sf_invite_event_division)
        club_2015_open_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_open_sf_invite_teams_unique_ordered, Division_Soup.club_2015_open_sf_invite_event_division)
        club_2015_womxns_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_womxns_sf_invite_teams_unique_ordered, Division_Soup.club_2015_womxns_sf_invite_event_division)
        club_2015_mixed_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_mixed_pf_finale_teams_unique_ordered, Division_Soup.club_2015_mixed_pf_finale_event_division)
        club_2015_open_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_open_pf_finale_teams_unique_ordered, Division_Soup.club_2015_open_pf_finale_event_division)
        club_2015_womxns_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_womxns_pf_finale_teams_unique_ordered, Division_Soup.club_2015_womxns_pf_finale_event_division)
        club_2015_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_mixed_nationals_teams_unique_ordered, Division_Soup.club_2015_mixed_nationals_event_division)
        club_2015_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_open_nationals_teams_unique_ordered, Division_Soup.club_2015_open_nationals_event_division)
        club_2015_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2015_womxns_nationals_teams_unique_ordered, Division_Soup.club_2015_womxns_nationals_event_division)
        club_2016_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_mixed_us_open_teams_unique_ordered, Division_Soup.club_2016_mixed_us_open_event_division)
        club_2016_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_open_us_open_teams_unique_ordered, Division_Soup.club_2016_open_us_open_event_division)
        club_2016_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_womxns_us_open_teams_unique_ordered, Division_Soup.club_2016_womxns_us_open_event_division)
        club_2016_mixed_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_mixed_es_challenge_teams_unique_ordered, Division_Soup.club_2016_mixed_es_challenge_event_division)
        club_2016_open_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_open_es_challenge_teams_unique_ordered, Division_Soup.club_2016_open_es_challenge_event_division)
        club_2016_womxns_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_womxns_es_challenge_teams_unique_ordered, Division_Soup.club_2016_womxns_es_challenge_event_division)
        club_2016_mixed_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_mixed_pe_challenge_teams_unique_ordered, Division_Soup.club_2016_mixed_pe_challenge_event_division)
        club_2016_open_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_open_pe_challenge_teams_unique_ordered, Division_Soup.club_2016_open_pe_challenge_event_division)
        club_2016_womxns_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_womxns_pe_challenge_teams_unique_ordered, Division_Soup.club_2016_womxns_pe_challenge_event_division)
        club_2016_mixed_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_mixed_sf_invite_teams_unique_ordered, Division_Soup.club_2016_mixed_sf_invite_event_division)
        club_2016_open_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_open_sf_invite_teams_unique_ordered, Division_Soup.club_2016_open_sf_invite_event_division)
        club_2016_womxns_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_womxns_sf_invite_teams_unique_ordered, Division_Soup.club_2016_womxns_sf_invite_event_division)
        club_2016_mixed_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_mixed_pf_finale_teams_unique_ordered, Division_Soup.club_2016_mixed_pf_finale_event_division)
        club_2016_open_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_open_pf_finale_teams_unique_ordered, Division_Soup.club_2016_open_pf_finale_event_division)
        club_2016_womxns_pf_finale_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_womxns_pf_finale_teams_unique_ordered, Division_Soup.club_2016_womxns_pf_finale_event_division)
        club_2016_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_mixed_nationals_teams_unique_ordered, Division_Soup.club_2016_mixed_nationals_event_division)
        club_2016_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_open_nationals_teams_unique_ordered, Division_Soup.club_2016_open_nationals_event_division)
        club_2016_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2016_womxns_nationals_teams_unique_ordered, Division_Soup.club_2016_womxns_nationals_event_division)
        club_2017_mixed_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_mixed_pe_challenge_teams_unique_ordered, Division_Soup.club_2017_mixed_pe_challenge_event_division)
        club_2017_open_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_open_pe_challenge_teams_unique_ordered, Division_Soup.club_2017_open_pe_challenge_event_division)
        club_2017_womxns_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_womxns_pe_challenge_teams_unique_ordered, Division_Soup.club_2017_womxns_pe_challenge_event_division)
        club_2017_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_mixed_us_open_teams_unique_ordered, Division_Soup.club_2017_mixed_us_open_event_division)
        club_2017_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_open_us_open_teams_unique_ordered, Division_Soup.club_2017_open_us_open_event_division)
        club_2017_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_womxns_us_open_teams_unique_ordered, Division_Soup.club_2017_womxns_us_open_event_division)
        club_2017_mixed_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_mixed_sf_invite_teams_unique_ordered, Division_Soup.club_2017_mixed_sf_invite_event_division)
        club_2017_open_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_open_sf_invite_teams_unique_ordered, Division_Soup.club_2017_open_sf_invite_event_division)
        club_2017_womxns_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_womxns_sf_invite_teams_unique_ordered, Division_Soup.club_2017_womxns_sf_invite_event_division)
        club_2017_mixed_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_mixed_es_challenge_teams_unique_ordered, Division_Soup.club_2017_mixed_es_challenge_event_division)
        club_2017_open_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_open_es_challenge_teams_unique_ordered, Division_Soup.club_2017_open_es_challenge_event_division)
        club_2017_womxns_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_womxns_es_challenge_teams_unique_ordered, Division_Soup.club_2017_womxns_es_challenge_event_division)
        club_2017_mixed_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_mixed_pro_championships_teams_unique_ordered, Division_Soup.club_2017_mixed_pro_championships_event_division)
        club_2017_open_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_open_pro_championships_teams_unique_ordered, Division_Soup.club_2017_open_pro_championships_event_division)
        club_2017_womxns_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_womxns_pro_championships_teams_unique_ordered, Division_Soup.club_2017_womxns_pro_championships_event_division)
        club_2017_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_mixed_nationals_teams_unique_ordered, Division_Soup.club_2017_mixed_nationals_event_division)
        club_2017_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_open_nationals_teams_unique_ordered, Division_Soup.club_2017_open_nationals_event_division)
        club_2017_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2017_womxns_nationals_teams_unique_ordered, Division_Soup.club_2017_womxns_nationals_event_division)
        club_2018_mixed_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_mixed_pe_challenge_teams_unique_ordered, Division_Soup.club_2018_mixed_pe_challenge_event_division)
        club_2018_open_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_open_pe_challenge_teams_unique_ordered, Division_Soup.club_2018_open_pe_challenge_event_division)
        club_2018_womxns_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_womxns_pe_challenge_teams_unique_ordered, Division_Soup.club_2018_womxns_pe_challenge_event_division)
        club_2018_mixed_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_mixed_sf_invite_teams_unique_ordered, Division_Soup.club_2018_mixed_sf_invite_event_division)
        club_2018_open_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_open_sf_invite_teams_unique_ordered, Division_Soup.club_2018_open_sf_invite_event_division)
        club_2018_womxns_sf_invite_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_womxns_sf_invite_teams_unique_ordered, Division_Soup.club_2018_womxns_sf_invite_event_division)
        club_2018_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_mixed_us_open_teams_unique_ordered, Division_Soup.club_2018_mixed_us_open_event_division)
        club_2018_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_open_us_open_teams_unique_ordered, Division_Soup.club_2018_open_us_open_event_division)
        club_2018_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_womxns_us_open_teams_unique_ordered, Division_Soup.club_2018_womxns_us_open_event_division)
        club_2018_mixed_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_mixed_es_challenge_teams_unique_ordered, Division_Soup.club_2018_mixed_es_challenge_event_division)
        club_2018_open_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_open_es_challenge_teams_unique_ordered, Division_Soup.club_2018_open_es_challenge_event_division)
        club_2018_womxns_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_womxns_es_challenge_teams_unique_ordered, Division_Soup.club_2018_womxns_es_challenge_event_division)
        club_2018_mixed_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_mixed_pro_championships_teams_unique_ordered, Division_Soup.club_2018_mixed_pro_championships_event_division)
        club_2018_open_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_open_pro_championships_teams_unique_ordered, Division_Soup.club_2018_open_pro_championships_event_division)
        club_2018_womxns_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_womxns_pro_championships_teams_unique_ordered, Division_Soup.club_2018_womxns_pro_championships_event_division)
        club_2018_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_mixed_nationals_teams_unique_ordered, Division_Soup.club_2018_mixed_nationals_event_division)
        club_2018_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_open_nationals_teams_unique_ordered, Division_Soup.club_2018_open_nationals_event_division)
        club_2018_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2018_womxns_nationals_teams_unique_ordered, Division_Soup.club_2018_womxns_nationals_event_division)
        club_2019_mixed_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_mixed_pe_challenge_teams_unique_ordered, Division_Soup.club_2019_mixed_pe_challenge_event_division)
        club_2019_open_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_open_pe_challenge_teams_unique_ordered, Division_Soup.club_2019_open_pe_challenge_event_division)
        club_2019_womxns_pe_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_womxns_pe_challenge_teams_unique_ordered, Division_Soup.club_2019_womxns_pe_challenge_event_division)
        club_2019_mixed_sf_invite_oh_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_mixed_sf_invite_oh_teams_unique_ordered, Division_Soup.club_2019_mixed_sf_invite_oh_event_division)
        club_2019_open_sf_invite_oh_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_open_sf_invite_oh_teams_unique_ordered, Division_Soup.club_2019_open_sf_invite_oh_event_division)
        club_2019_womxns_sf_invite_oh_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_womxns_sf_invite_oh_teams_unique_ordered, Division_Soup.club_2019_womxns_sf_invite_oh_event_division)
        club_2019_mixed_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_mixed_us_open_teams_unique_ordered, Division_Soup.club_2019_mixed_us_open_event_division)
        club_2019_open_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_open_us_open_teams_unique_ordered, Division_Soup.club_2019_open_us_open_event_division)
        club_2019_womxns_us_open_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_womxns_us_open_teams_unique_ordered, Division_Soup.club_2019_womxns_us_open_event_division)
        club_2019_mixed_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_mixed_es_challenge_teams_unique_ordered, Division_Soup.club_2019_mixed_es_challenge_event_division)
        club_2019_open_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_open_es_challenge_teams_unique_ordered, Division_Soup.club_2019_open_es_challenge_event_division)
        club_2019_womxns_es_challenge_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_womxns_es_challenge_teams_unique_ordered, Division_Soup.club_2019_womxns_es_challenge_event_division)
        club_2019_mixed_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_mixed_pro_championships_teams_unique_ordered, Division_Soup.club_2019_mixed_pro_championships_event_division)
        club_2019_open_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_open_pro_championships_teams_unique_ordered, Division_Soup.club_2019_open_pro_championships_event_division)
        club_2019_womxns_pro_championships_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_womxns_pro_championships_teams_unique_ordered, Division_Soup.club_2019_womxns_pro_championships_event_division)
        club_2019_mixed_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_mixed_nationals_teams_unique_ordered, Division_Soup.club_2019_mixed_nationals_event_division)
        club_2019_open_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_open_nationals_teams_unique_ordered, Division_Soup.club_2019_open_nationals_event_division)
        club_2019_womxns_nationals_teams_divisions_dict = Teams_Division_Dict(Teams_Seeds_Teams_Unique_Ordered.club_2019_womxns_nationals_teams_unique_ordered, Division_Soup.club_2019_womxns_nationals_event_division)

teams_divisions_list = [Teams_Divisions.club_2010_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2010_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2010_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2011_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2011_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2011_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2012_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2012_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2012_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2012_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2012_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2012_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2013_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2013_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2013_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2013_open_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2013_womxns_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2013_mixed_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2013_open_es_challenge_co_teams_divisions_dict
,Teams_Divisions.club_2013_womxns_es_challenge_co_teams_divisions_dict
,Teams_Divisions.club_2013_mixed_es_challenge_wa_teams_divisions_dict
,Teams_Divisions.club_2013_womxns_esf_challenge_wa_teams_divisions_dict
,Teams_Divisions.club_2013_mixed_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2013_open_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2013_womxns_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2013_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2013_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2013_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2014_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2014_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2014_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2014_open_pe_challenge_va_teams_divisions_dict
,Teams_Divisions.club_2014_womxns_pe_challenge_va_teams_divisions_dict
,Teams_Divisions.club_2014_mixed_pe_challenge_ny_teams_divisions_dict
,Teams_Divisions.club_2014_mixed_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2014_open_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2014_womxns_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2014_mixed_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2014_open_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2014_womxns_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2014_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2014_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2014_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2015_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2015_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2015_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2015_mixed_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2015_open_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2015_womxns_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2015_mixed_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2015_open_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2015_womxns_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2015_mixed_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2015_open_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2015_womxns_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2015_mixed_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2015_open_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2015_womxns_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2015_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2015_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2015_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2016_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2016_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2016_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2016_mixed_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2016_open_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2016_womxns_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2016_mixed_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2016_open_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2016_womxns_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2016_mixed_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2016_open_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2016_womxns_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2016_mixed_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2016_open_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2016_womxns_pf_finale_teams_divisions_dict
,Teams_Divisions.club_2016_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2016_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2016_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2017_mixed_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2017_open_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2017_womxns_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2017_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2017_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2017_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2017_mixed_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2017_open_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2017_womxns_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2017_mixed_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2017_open_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2017_womxns_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2017_mixed_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2017_open_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2017_womxns_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2017_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2017_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2017_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2018_mixed_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2018_open_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2018_womxns_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2018_mixed_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2018_open_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2018_womxns_sf_invite_teams_divisions_dict
,Teams_Divisions.club_2018_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2018_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2018_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2018_mixed_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2018_open_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2018_womxns_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2018_mixed_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2018_open_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2018_womxns_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2018_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2018_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2018_womxns_nationals_teams_divisions_dict
,Teams_Divisions.club_2019_mixed_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2019_open_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2019_womxns_pe_challenge_teams_divisions_dict
,Teams_Divisions.club_2019_mixed_sf_invite_oh_teams_divisions_dict
,Teams_Divisions.club_2019_open_sf_invite_oh_teams_divisions_dict
,Teams_Divisions.club_2019_womxns_sf_invite_oh_teams_divisions_dict
,Teams_Divisions.club_2019_mixed_us_open_teams_divisions_dict
,Teams_Divisions.club_2019_open_us_open_teams_divisions_dict
,Teams_Divisions.club_2019_womxns_us_open_teams_divisions_dict
,Teams_Divisions.club_2019_mixed_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2019_open_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2019_womxns_es_challenge_teams_divisions_dict
,Teams_Divisions.club_2019_mixed_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2019_open_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2019_womxns_pro_championships_teams_divisions_dict
,Teams_Divisions.club_2019_mixed_nationals_teams_divisions_dict
,Teams_Divisions.club_2019_open_nationals_teams_divisions_dict
,Teams_Divisions.club_2019_womxns_nationals_teams_divisions_dict]

class Teams_DF:
    def __init__(self, teams_divisions):
        self.teams_divisions = teams_divisions
    
    def full_teams(self):
        full_teams = []
        for d in self.teams_divisions:
            full_teams += d.teams()
        return full_teams
    
    def full_divisions(self):
        full_divisions = []
        for d in self.teams_divisions:
            full_divisions += d.divisions()
        return full_divisions

    def teams_dictionary(self):
        teams_divisions_dictionary = dict(zip(self.full_teams(), self.full_divisions()))
        return teams_divisions_dictionary
    
    def teams_unique(self):
        teams_unique = list(self.teams_dictionary().keys())
        return teams_unique

    def divisions(self):
        divisions = list(self.teams_dictionary().values())
        return divisions
    
    def nulls(self):
        nulls = ['null'] * len(self.teams_unique())
        return nulls
    
    def teams_df(self):
        teams = pd.DataFrame({'team_name': self.teams_unique(), 'team_city': self.nulls(), 'division': self.divisions(), 'region': self.nulls()})
        teams.index += 1
        return teams

class Teams:
    teams = Teams_DF(teams_divisions_list).teams_df()

print(Teams.teams)